### ISSUE TITLE
NPE sometimes thrown on PlayerAdvancementDoneEvent

### ISSUE THREAD

**Issue by Cuube** [infinitygrid/Mercury#1]
No advancement message in Discord, let alone in-game.
Stacktrace:
```java
[12:30:17 ERROR]: Could not pass event PlayerAdvancementDoneEvent to Mercury v1.0
java.lang.NullPointerException: null cannot be cast to non-null type net.kyori.adventure.text.TranslatableComponent
        at net.infinitygrid.mercury.discord.DiscordLivechat.sendAchievementMessage(DiscordLivechat.kt:64) ~[?:?]
        at net.infinitygrid.mercury.discord.MinecraftSysChatListener.on(MinecraftSysChatListener.kt:17) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.jar:git-Purpur-1191]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Purpur-1191]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Purpur-1191]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Purpur-1191]
        at net.minecraft.server.PlayerAdvancements.award(PlayerAdvancements.java:298) ~[?:?]
        at net.minecraft.advancements.CriterionTrigger$Listener.run(CriterionTrigger.java:35) ~[?:?]
        at net.minecraft.advancements.critereon.SimpleCriterionTrigger.trigger(SimpleCriterionTrigger.java:73) ~[?:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.a(InventoryChangeTrigger.java:55) ~[?:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.trigger(InventoryChangeTrigger.java:51) ~[?:?]
        at net.minecraft.server.level.ServerPlayer$2.slotChanged(ServerPlayer.java:311) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:269) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:232) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCreativeModeSlot(ServerGamePacketListenerImpl.java:3048) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:18) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:7) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Purpur-1191]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[patched_1.17.jar:git-Purpur-1191]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Purpur-1191]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[patched_1.17.jar:git-Purpur-1191]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[patched_1.17.jar:git-Purpur-1191]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1360) ~[patched_1.17.jar:git-Purpur-1191]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1271) ~[patched_1.17.jar:git-Purpur-1191]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.jar:git-Purpur-1191]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Cuube** [comment]
Already fixed this in some commit (don't know which) by a simple null check -> return. Event was also called when player unlocks a recipe which is not an advancement or a challange and therefore has had no message object that could be casted
